import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import dotenv from "dotenv";

// Load environment variables from .env file
dotenv.config();

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD if you want to view the source, please visit the github repository of this plugin */ `;

const prod = (process.argv[2] === "production");

// Build-time environment variable injection
const define = {
  "process.env.MYSCRIPT_APPLICATION_KEY": JSON.stringify(process.env.MYSCRIPT_APPLICATION_KEY || ""),
  "process.env.MYSCRIPT_HMAC_KEY": JSON.stringify(process.env.MYSCRIPT_HMAC_KEY || ""),
  "process.env.MYSCRIPT_LANGUAGE": JSON.stringify(process.env.MYSCRIPT_LANGUAGE || "en_US"),
};

const commonConfig = {
  bundle: true,
  define,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
};

const mainContext = await esbuild.context({
  ...commonConfig,
  banner: { js: banner },
  entryPoints: ["main.ts"],
  outfile: "main.js",
  format: "cjs",
  target: "es2018",
});

if (prod) {
  await mainContext.rebuild();
  process.exit(0);
} else {
  await mainContext.watch();
}
